/**
 * Content source. Snapshot of the GM's PUBLIC vault, generated by
 * `scripts/build-content.ts` into `src/generated/content.ts`.
 *
 * Components and scripts that need the content tree import from here, not
 * from `src/generated` directly — that way swapping to a Supabase-backed
 * loader later (stage C `--execute`) is a one-file change.
 */
export { contentTree } from '../generated/content'
